name: Reboot ASG on PR Merge

on:
  push:
    branches:
      - main

jobs:
  reboot-asg:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - name: Debug GitHub OIDC Token
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Event Name: ${{ github.event_name }}"

      - name: Configure AWS Credentials (via OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ${{ secrets.AWS_IAM_REGION }}
          audience: sts.amazonaws.com

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Send API request to reboot ASG
        run: |
          echo "Using API Gateway URL: ${{ secrets.API_GATEWAY_URL }}"
          curl -X POST "${{ secrets.API_GATEWAY_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"asg_name": "NairobiIoTSimASG", "source": "GitHub Actions"}'
