name: Reboot ASG on PR Merge

on:
  push:
    branches:
      - main

jobs:
  reboot-asg:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials (via OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::235494823312:role/github-actions
          aws-region: us-east-1

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Debug API Gateway Request
        run: |
          echo "Using API Gateway URL: ${{ secrets.API_GATEWAY_URL }}"
          curl -v -X POST "${{ secrets.API_GATEWAY_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"asg_name": "NairobiIoTSimASG"}'
