jobs:
  scale-down-asg:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials (via OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/github-actions
          aws-region: us-east-2

      - name: Send API request to scale down ASG
        run: |
          curl -X POST "${{ secrets.API_GATEWAY_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"asg_name": "NairobiIoTSimASG"}'
